---
- name: run optional versionscheck
  ansible.builtin.include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- name: install acmetool from fixed url
  become: true
  ansible.builtin.apt:
    deb: "{{ acmetool_fix__deb }}"
